
version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container_2:/data/db
      - ./mongo-file:/file
    networks:
      - social

  redis:
    image: "redis:alpine"

    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-dt:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - social

  rabbitmq:
    image: rabbitmq:3.12.7-management
    volumes:
      - /media/NewHDD/erp/.docker/rabbitmq/etc/:/var/run/rabbitmq/
      - /media/NewHDD/erp/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - /media/NewHDD/erp/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      # provide your credentials here
      - RABBITMQ_DEFAULT_PASS=wilad0304
      - RABBITMQ_DEFAULT_USER=wilad
    networks:
      - social
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: quyhot
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data
    networks:
      - social
    restart: always

volumes:
  mongodb_data_container_2:

networks:
  social:
    driver: bridge
