
version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=egosnet
      - MONGO_INITDB_ROOT_PASSWORD=pPJscOMYgBYHtwY
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container_2:/data/db
      - ./mongo-file:/file
    networks:
      - social

  redis:
    image: "redis:alpine"

    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-dt:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - social

  rabbitmq:
    image: rabbitmq:3.12.7-management
    volumes:
      - /media/NewHDD/erp/.docker/rabbitmq/etc/:/var/run/rabbitmq/
      - /media/NewHDD/erp/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - /media/NewHDD/erp/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      # provide your credentials here
      - RABBITMQ_DEFAULT_PASS=wilad0304
      - RABBITMQ_DEFAULT_USER=wilad
    networks:
      - social
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: quyhot
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data
    networks:
      - social
    restart: always

  appserver:
    image: "sn-app-server:latest"
    ports:
      - '8009:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB: ''
      DB_USER: 'egosnet'
      DB_PASS: 'pPJscOMYgBYHtwY'
      DB_SERVERS: 'mongodb:27017'
      SECRET_KEY: 'cur$$123$$jl1haG'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      AUTHORIZATION_CMS_URL: "http://appserver:3000/authorization"
      INTERNAL_TOKEN: '123'
    networks:
      - carpla
    restart: always

  feed:
    image: "sn-feed-service:latest"
    ports:
      - '8009:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB: 'sn-feed-service'
      DB_USER: 'egosnet'
      DB_PASS: 'pPJscOMYgBYHtwY'
      DB_SERVERS: 'mongodb:27017'
      SECRET_KEY: 'cur$$123$$jl1haG'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      AUTHORIZATION_CMS_URL: "http://appserver:3000/authorization"
      INTERNAL_TOKEN: '123'
    networks:
      - carpla
    restart: always


volumes:
  mongodb_data_container_2:

networks:
  social:
    driver: bridge
